version: 2.1
orbs:
  docker: circleci/docker@1.0.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run build
          command: docker-compose up --abort-on-container-exit
